### ISSUE TITLE
Parry doesn't show the inutitive modifiers if done via token action hud

### ISSUE THREAD

**Issue by Agnestorm** [sp0ken/token-action-hud-forbidden-lands#3]
As the titles states. Screenshots for reference:

Character sheet combat actions:
![image](https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/128893666/7e8b8244-7271-4cec-975d-ec2de2e719ee)

Token Action HUD combat actions: 
![image](https://github.com/sp0ken/token-action-hud-forbidden-lands/assets/128893666/829382ce-91dd-44ee-80e0-1b7c26a1f9d5)

**Comment by sp0ken** [comment]
Should be fixed in the latest version by `shift-clicking` the weapon you want to parry with

**Comment by Agnestorm** [comment]
> Should be fixed in the latest version by `shift-clicking` the weapon you want to parry with

Just came back to FBL after a couple months and tried this. It doesn't work. It still doesn't show the modifiers I spoke about.

**Comment by sp0ken** [comment]
Can you try version 0.6 (the latest)? I, somehow, botched the publication of the previous release which included this feature.

**Comment by Agnestorm** [comment]
Apologies for the late response, but yes, it works as intended now. Thanks.
